Update enchants.json (Mana Steal, Smarty Pants, and Dragon Tracer) fixed formatting
BiscuitDevelopment/SkyblockAddons-Data pull request #4
Opened 2021-06-06 22:52 UTC by Cobble8

2021-06-06 23:16 UTC, ImRodry requested changes

2021-06-06 23:16 UTC, ImRodry commented on skyblock/enchants.json
> +    },
Formatting please

2021-06-06 23:16 UTC, ImRodry commented on skyblock/enchants.json
> +      "goodLevel": 0,
How is the good level 0?

2021-06-06 23:16 UTC, ImRodry commented on skyblock/enchants.json
> +    "smarty pants":{
formatting

2021-06-06 23:16 UTC, ImRodry commented on skyblock/enchants.json
> +       "goodLevel": 0,
how is the good level 0?

2021-06-07 04:59 UTC, Phoube commented on skyblock/enchants.json
> +       "goodLevel": 0,
Good level is the maximum level you can craft from an enchanting table, so until we make a better system for it, I think smarty pants, which is uncraftable, can stay at good=level 0

2021-06-09 15:37 UTC, closed without merging

2021-06-09 15:38 UTC, Phoube commented
Made some edits and merged. Thanks for the contrib! :D